# -*- coding: utf-8 -*-
"""Iris_ANN_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4zMQryyrOIAO5FwUZ7QvvIKeN0kjr7d
"""

import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch

import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

torch.manual_seed(42)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("vikrishnan/iris-dataset")

print("Path to dataset files:", path)

for file in os.listdir(path):
  print(file)

file_path = os.path.join(path, "iris.data.csv")
df = pd.read_csv(file_path)
df

df.shape

df['Iris-setosa'].value_counts()

df.shape

le = LabelEncoder()
df['Iris-setosa'] = le.fit_transform(df['Iris-setosa'])

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

x_train , x_test,y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

class Iris_Dataset(Dataset):
  def __init__(self,x,y):
    self.x = torch.tensor(x,dtype=torch.float32)
    self.y = torch.tensor(y,dtype=torch.long)
    self.len = self.x.shape[0]
  def __len__(self):
    return self.len
  def __getitem__(self, index):
    return self.x[index], self.y[index]

train_dataset = Iris_Dataset(x_train , y_train)
test_Dataset = Iris_Dataset(x_test,y_test)

train_loader = DataLoader(dataset=train_dataset,batch_size=10,shuffle=True)
test_loader = DataLoader(dataset=test_Dataset,batch_size=10,shuffle=False)

class ANN_Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(4,32),
        nn.ReLU(),
        nn.Linear(32,16),
        nn.ReLU(),
        nn.Linear(16,3) # Changed from 1 to 3 to match the number of classes
    )
  def forward(self,x):
    return self.layers(x)

model = ANN_Model().to(device)

epochs = 20
learning_rate = 0.1

loss = nn.CrossEntropyLoss()
model = ANN_Model()
optimizer = optim.Adam(model.parameters(),lr = learning_rate)

for epoch in range(epochs):
  total_epochs = 0
  for feature , label in train_loader:

    output = model(feature)
    criterion = loss(output,label)
    optimizer.zero_grad()
    criterion.backward()
    optimizer.step()
  total_epochs += criterion.item()
  avg_loss = total_epochs/len(train_loader)
  print(f"Epochs :{epoch+1} , loss  :{avg_loss}")

model.eval()



total = 0
correct = 0
with torch.no_grad():
  for feature,label in test_loader:
    output = model(feature)
    _, predicted = torch.max(output,1)
    total += label.size(0)
    correct = correct + (predicted == label).sum().item()
print(100*(correct/total))

